[workspace]
resolver = "2"
members = [
    "orchestrator",
    "stt-service", 
    "tts-service"
]

[workspace.dependencies]
tokio = { version = "1.40", features = ["full"] }
axum = "0.7"
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0"
